onboarding = false

[terminal]
shell_mode = "auto"

[ui]
tab_bar_position = "top"
sidebar_start_collapsed = false

[theme]
name = "tokyo-night"

[theme.custom]
panel_bg = "#0e0e12"

[keys]
prefix = "alt+a"
switch_tab = "alt+1..9"
split_horizontal = "alt+h"
split_vertical = "alt+v"
new_tab = "alt+n"
close_pane = "alt+q"
close_tab = "alt+shift+q"
reload_config = "alt+shift+r"
toggle_sidebar = "alt+s"
rename_tab = "alt+shift+t"
resize_mode = "prefix+r"
swap_pane_left = "alt+left"
swap_pane_right = "alt+right"
swap_pane_up = "alt+up"
swap_pane_down = "alt+down"

[[keys.command]]
key = "alt+e"
type = "popup"
command = "emacsclient -c -a 'emacs' --nw"
description = "run emacs"
width = "80%"
height = "80%"
